# -*- coding: utf-8 -*-

CONSUMER_KEY = 'TWITTER CLIENT\'s CONSUMER KEY'
CONSUMER_SECRET = 'TWITTER CLIENT\'s CONSUMER SECRET'
REQUEST_TOKEN_SESSION_KEY = '_request_token'
MONGO_HOST = 'MONGO \'s HOST NAME'
